using UnityEngine;
using System.Collections;
using System;

public class BaseMovementMessage : BaseMessage
{
    private Vector2 _movement;
    public virtual Vector2 Movement
    {
        get
        {
            return this._movement;
        }

        protected set
        {
            this._movement = value;
        }
    }

    //Movement Messages do not have OriginObjects-- they are usually generated by managers
    public BaseMovementMessage(Vector2 movementIn) : base(null)
    {
        this.Movement = movementIn;
    }

    //Movement Messages do not have OriginObjects-- they are usually generated by managers
    public override GameObject OriginObject
    {
        get
        {
            throw new NotImplementedException();
        }
    }

}
